name: core
description: A new Flutter package.
version: 0.0.0
homepage: https://github.com/Dennis-Mwea/flutter-clean-architecture
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.2.5
  auto_route: ^7.1.0
  logger: ^2.0.2+1
  get_it: ^7.6.0
  injectable: ^2.1.1
  adaptive_dialog: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.2
  auto_route_generator: ^7.0.0
  injectable_generator: ^2.1.5

flutter:
